jdk: oraclejdk8
language: java

script: 

  - "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
  - "mvn clean install -P test-business"
  
after_success: 
  - "mvn clean test-business jacoco:report coveralls:report"

